DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(AUTHOR_ID BIGINT PRIMARY KEY, LAST_NAME VARCHAR(255) NOT NULL, FIRST_NAME VARCHAR(255) NOT NULL );

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(GENRE_ID BIGINT PRIMARY KEY, GENRE VARCHAR(255) NOT NULL );

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
BOOK_ID BIGINT PRIMARY KEY,
AUTHOR_ID BIGINT,
GENRE_ID BIGINT,
TITLE VARCHAR(255) NOT NULL,
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID),
FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID));
